spring:
  # 기본으로 활성화할 프로필을 'local'로 지정합니다.
  # 서버 배포 시 실행 옵션으로 'prod'를 지정하면 이 설정이 무시되고 prod 설정이 활성화됩니다.
  profiles:
    active: local
  server:
    forward-header-strategy: framework

  # JPA (Java Persistence API) 설정
  jpa:
    hibernate:
      ddl-auto: update # 애플리케이션 실행 시 DB 스키마 자동 업데이트
    properties:
      hibernate:
        format_sql: true # SQL 쿼리를 보기 좋게 포맷팅
    show-sql: true # 실행되는 SQL 쿼리를 로그에 표시

  # 파일 업로드 용량 설정
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

logging:
  level:
    # SQL 파라미터 값을 로그에 표시 (디버깅에 유용)
    org.hibernate.type.descriptor.sql: trace

# Swagger (API 문서) 설정
springdoc:
  swagger-ui:
    path: /swagger-ui.html   # Swagger UI 접속 경로
    tags-sorter: alpha       # API 그룹을 알파벳 순으로 정렬
    operations-sorter: alpha # API 를 알파벳 순으로 정렬
  api-docs:
    path: /api-docs          # API 스펙(JSON) 경로
  info:
    title: "AI AutoGrader API"
    description: "딥러닝 기초 과제 자동 채점 시스템 API 명세서"
    version: "v1.0.0"

evaluator:
  script:
    path: /data/class/ta/twkk0819/evaluator-py/Evaluator-Python/grading_script.py